Première version publique
Kozea/www-community pull request #1
Opened 2018-06-12 15:39 UTC by liZe

2018-06-12 16:01 UTC, grewn0uille requested changes

2018-06-12 16:01 UTC, grewn0uille commented on static/sass/style.sass
> +    margin: 1.5em 0 0.5em
Ordre alpha

2018-06-13 08:36 UTC, grewn0uille approved these changes

2018-06-13 08:57 UTC, grewn0uille commented
[Plateforme de test](https://test-www-community.kozea.fr/)

2018-06-14 13:29 UTC, paradoxxxzero requested changes
Il y a quelques changement dans la gestion du Makefile de MakeCitron à faire

2018-06-14 13:29 UTC, paradoxxxzero commented on .gitignore
> +MakeCitron.Makefile
Il manque un retour à la ligne de fin de fichier non ?

2018-06-14 13:29 UTC, paradoxxxzero commented on Makefile
> +include config.Makefile
Les Makefile MakeCitron sont désormais basés sur un dot file MakeCitron.Makefile (en gros faut télécharger pour la première fois ce fichier: https://github.com/Kozea/MakeCitron/blob/v1/dots/MakeCitron.Makefile et l'ajouter au projet puis remplacer ces 17 premières lignes par un `include MakeCitron.Makefile` cf exemple: https://github.com/Kozea/apparatus/blob/master/Makefile)

2018-06-14 13:29 UTC, paradoxxxzero commented on Makefile
> +lint-pytho%:
Ne pas mettre les règles de matching flou (terminant en %) dans le Makefile de base (l'intérêt réside uniquement dans les makefile inclus pour pouvoir les surcharger)

2018-06-14 13:29 UTC, paradoxxxzero commented on Makefile
> +check-pytho%:
cf l20, https://github.com/Kozea/www-community/pull/1/files#diff-b67911656ef5d18c4ae36cb6741b7965R20

2018-06-14 15:14 UTC, clemenceprem commented
@liZe il manque l'adresse twitter @kozeacommunity dans About. et c'est Freenode et pas Freenonde

2018-06-14 15:15 UTC, clemenceprem requested changes
@liZe va voir le commentaire

2018-06-14 16:22 UTC, paradoxxxzero approved these changes

2018-06-22 12:47 UTC, clemenceprem commented
@liZe j'ai ouvert un autre compte twitter : @communitykozea Est-ce que tu peux changer l'adresse sur le www stp ?

2018-06-27 13:22 UTC, clemenceprem approved these changes

2018-06-28 13:36 UTC, merged