Design
Kozea/www-community pull request #4
Opened 2018-07-11 13:53 UTC by annabellou

Style intégré d'après la maquette
https://drive.google.com/open?id=1CE27_YHwmaCMn0IinPrbleTixDrfmAzv

2018-07-11 20:34 UTC, liZe requested changes
À part le problème d'import, ça me plaît :+1:.

2018-07-11 20:34 UTC, liZe commented on static/css/style.sass.css
> +@import url("https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700");
Tu as un problème : tes fontes sont importées autant de fois que le fichier `_variables.sass` est importé. Il faut soit mettre les `@import` dans `style.sass`, soit le mettre dans un fichier à part qui est importé par `style.sass`.

2018-07-12 08:30 UTC, annabellou commented
Problème d'import corrigé ! Merci pour la review

2018-07-17 08:52 UTC, clemenceprem approved these changes

2018-07-17 08:54 UTC, liZe approved these changes

2018-07-17 09:01 UTC, merged